
package a.b.c;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "web-service-client", targetNamespace = "http://service.web.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WebServiceClient {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getString", targetNamespace = "http://service.web.com/", className = "a.b.c.GetString")
    @ResponseWrapper(localName = "getStringResponse", targetNamespace = "http://service.web.com/", className = "a.b.c.GetStringResponse")
    @Action(input = "http://service.web.com/web-service-client/getStringRequest", output = "http://service.web.com/web-service-client/getStringResponse")
    public String getString();

}
