
package a.b.c;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@javax.xml.ws.WebServiceClient(name = "WebServiceClientService", targetNamespace = "http://service.web.com/", wsdlLocation = "http://localhost:9999/WebServiceClient?wsdl")
public class WebServiceClientService
    extends Service
{

    private final static URL WEBSERVICECLIENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICECLIENTSERVICE_EXCEPTION;
    private final static QName WEBSERVICECLIENTSERVICE_QNAME = new QName("http://service.web.com/", "WebServiceClientService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/WebServiceClient?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICECLIENTSERVICE_WSDL_LOCATION = url;
        WEBSERVICECLIENTSERVICE_EXCEPTION = e;
    }

    public WebServiceClientService() {
        super(__getWsdlLocation(), WEBSERVICECLIENTSERVICE_QNAME);
    }

    public WebServiceClientService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICECLIENTSERVICE_QNAME, features);
    }

    public WebServiceClientService(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICECLIENTSERVICE_QNAME);
    }

    public WebServiceClientService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICECLIENTSERVICE_QNAME, features);
    }

    public WebServiceClientService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceClientService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WebServiceClient
     */
    @WebEndpoint(name = "web-service-clientPort")
    public a.b.c.WebServiceClient getWebServiceClientPort() {
        return super.getPort(new QName("http://service.web.com/", "web-service-clientPort"), WebServiceClient.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebServiceClient
     */
    @WebEndpoint(name = "web-service-clientPort")
    public a.b.c.WebServiceClient getWebServiceClientPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.web.com/", "web-service-clientPort"), WebServiceClient.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICECLIENTSERVICE_EXCEPTION!= null) {
            throw WEBSERVICECLIENTSERVICE_EXCEPTION;
        }
        return WEBSERVICECLIENTSERVICE_WSDL_LOCATION;
    }

}
